### ISSUE TITLE
Dead comments, unclear filenames, insufficient readme

### ISSUE THREAD

**Issue by TheGreatWaves** [qwertybee/vending_machine_app#1]
>_**NOTE**_: Sorry in advance if some of the suggestions I make clashes with Django conventions. ( I'm unaware of them since I do not use it )

1). Commented out code is bad.
https://github.com/qwertybee/vending_machine_app/blob/7bb08b708d89677f898e03adc0e6f72d42a39efe/vending_machine_django/accounts/views.py#L13

1). Should maybe be referenced in the readme since it's important.

2). The name of the file does not reflect the content (Unless this is a Django specific style I'm unaware of, in that case I'm sorry.)
https://github.com/qwertybee/vending_machine_app/blob/e122900c27786a14d383e9fc971124466ddd4858/vending_machine_django/accounts/admin.py#L3

1). Maybe consider using another name rather than `pk` (I think it's a little unclear, though opinions may differ)
> https://github.com/qwertybee/vending_machine_app/blob/7bb08b708d89677f898e03adc0e6f72d42a39efe/vending_machine_django/accounts/views.py#L52
> https://github.com/qwertybee/vending_machine_app/blob/7bb08b708d89677f898e03adc0e6f72d42a39efe/vending_machine_django/accounts/views.py#L84
> https://github.com/qwertybee/vending_machine_app/blob/7bb08b708d89677f898e03adc0e6f72d42a39efe/vending_machine_django/accounts/views.py#L97
> https://github.com/qwertybee/vending_machine_app/blob/7bb08b708d89677f898e03adc0e6f72d42a39efe/vending_machine_django/accounts/views.py#L110

1). Filename does not reflect content.
https://github.com/qwertybee/vending_machine_app/blob/7bb08b708d89677f898e03adc0e6f72d42a39efe/vending_machine_django/accounts/apps.py

# Final Remarks
- Consider type annotation where applicable
- Variable names and function names are well chosen (Good job!)
- Could use more error checking where applicable
- Consider adding directory structure to your readme in order to make it more easily extendable. It's clear that there are dependencies everywhere within the project, like forms, models and admin (where you register files). It may be helpful to include brief information about each file and which you must extend in order to implement A, B, C (e.g Making Vending_Machine work requires 1. Declaring a new model in `models.py`, 2. registering the new model in `admin.py`, 3. making a VendingSerializer/ Vending form in `forms.py`)

**Comment by qwertybee** [comment]
Feedback much appreciated!
- Initially, I made my own UI and API that highly deviates from the commit with just the basic API integration so putting two versions in there can look like its mostly an irrelevant mess (.html, etc.)
- pk is the 'primary key' that refers to the unique id of content in the database.
- Django has quite a strict naming file convention to follow and auto-generated files (apps.py, admin.py, etc.) to form dependencies, there are little room for changes. Newcomers can be puzzled as to how it connects to one another since filenames are unclear at first.

Will be following through with cleaning up
